services:
  - type: web
    name: braille-api
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y liblouis-dev liblouis-data
      pip install -r requirements.txt
    startCommand: python main.py
