services:
  - type: web
    name: braille-api
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y liblouis-dev
      pip install -r requirements.txt
    startCommand: python app.py
